---
all:
  children:
    NCS540L:
      hosts:
        Hostname01:
          ansible_host: #Hostname01 IP Address#
          ansible_user: #Hostname01 username#
          ansible_password: #Hostname01 password#
    NCS540:
      hosts:
        Hostname02:
          ansible_host: #Hostname02 IP Address#
          ansible_user: #Hostname02 username#
          ansible_password: #Hostname02 password#
    NCS5500:
      hosts:
        Hostname03:
          ansible_host: #Hostname03 IP Address#
          ansible_user: #Hostname03 username#
          ansible_password: #Hostname03 password#
    ASR9900:
      hosts:
        Hostname04:
          ansible_host: #Hostname04 IP Address#
          ansible_user: #Hostname04 username#
          ansible_password: #Hostname04 password#
    CISCO8000:
      hosts:
        Hostname05:
          ansible_host: #Hostname05 IP Address#
          ansible_user: #Hostname05 username#
          ansible_password: #Hostname05 password#
    DHCP_Servers:
      hosts:
        Hostname06:
          ansible_host: #Hostname06 IP Address#
          ansible_user: #Hostname06 username#
          ansible_password: #Hostname06 password#
          ansible_become_password: #Hostname06 SUDU password#